### ISSUE TITLE
neo init causes a bug

### ISSUE THREAD

**Issue by eddiewang** [mozilla/neo#32]
```
const { commands } = require('../package.json');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

**Comment by eddiewang** [comment]
I'm a dummy - I forgot my work pc ran node 4... upgraded to node 6 and working fine now...

**Comment by stevechae** [comment]
The project's README says Node v4+ while it's clearly 6.0+...

**Comment by eliperelman** [comment]
@stevechae the project has since been updated to run against v4. Are you experiencing a problem using v4?

**Comment by stevechae** [comment]
My apologies, it seems that my neo version was at 2.2.1. I've updated to the latest and it seems fine now. :)
