### ISSUE TITLE
neo test results in build errors (JSON files)

### ISSUE THREAD

**Issue by ddho23** [mozilla/neo#47]
After creating a new project using neo v2.2.0, running "neo test" results in build errors related to loading JSON files. Running dev mode works fine.

ERROR in ./~/cheerio/package.json
Module build failed: SyntaxError: Unexpected token m in JSON at position 0
    at Object.parse (native)
    at Object.module.exports (/home/derekho/LikeMindNetworks/prototypes/react-proto/node_modules/json-loader/index.js:7:48)
 @ ./~/cheerio/index.js 11:18-38

ERROR in ./~/css-select/lib/procedure.json
Module build failed: SyntaxError: Unexpected token m in JSON at position 0
    at Object.parse (native)
    at Object.module.exports (/home/derekho/LikeMindNetworks/prototypes/react-proto/node_modules/json-loader/index.js:7:48)
 @ ./~/css-select/lib/compile.js 17:18-45

ERROR in ./~/entities/maps/xml.json
Module build failed: SyntaxError: Unexpected token m in JSON at position 0
    at Object.parse (native)
    at Object.module.exports (/home/derekho/LikeMindNetworks/prototypes/react-proto/node_modules/json-loader/index.js:7:48)
 @ ./~/htmlparser2/lib/Tokenizer.js 6:16-49

ERROR in ./~/entities/maps/entities.json
Module build failed: SyntaxError: Unexpected token m in JSON at position 0
    at Object.parse (native)
    at Object.module.exports (/home/derekho/LikeMindNetworks/prototypes/react-proto/node_modules/json-loader/index.js:7:48)
 @ ./~/htmlparser2/lib/Tokenizer.js 4:16-54

ERROR in ./~/entities/maps/legacy.json
Module build failed: SyntaxError: Unexpected token m in JSON at position 0
    at Object.parse (native)
    at Object.module.exports (/home/derekho/LikeMindNetworks/prototypes/react-proto/node_modules/json-loader/index.js:7:48)
 @ ./~/htmlparser2/lib/Tokenizer.js 5:16-52

ERROR in ./~/entities/maps/decode.json
Module build failed: SyntaxError: Unexpected token m in JSON at position 0
    at Object.parse (native)
    at Object.module.exports (/home/derekho/LikeMindNetworks/prototypes/react-proto/node_modules/json-loader/index.js:7:48)
 @ ./~/entities/lib/decode_codepoint.js 1:16-46

**Comment by eliperelman** [comment]
Heh, noticed that too, good catch. Hopefully should be fixed in #48.

**Comment by eliperelman** [comment]
Published to npm@2.2.1.
