### ISSUE TITLE
unable to npm install

### ISSUE THREAD

**Issue by moshmage** [mozilla/neo#73]
[here's a logtalk](https://gist.github.com/moshmage/98f90afa77dafe3d70de129b63e8dafc) though I think this is the important part

```logtalk
126406 warn enzyme@2.4.1 requires a peer of react@0.13.x || 0.14.x || ^15.0.0-0 but none was installed.
126407 verbose If you need help, you may report this error at:
126407 verbose     <https://github.com/npm/npm/issues>
126408 warn react-element-to-jsx-string@3.2.0 requires a peer of react@^0.14.8 || ^15.0.1 but none was installed.
126409 verbose If you need help, you may report this error at:
126409 verbose     <https://github.com/npm/npm/issues>
126410 warn react-addons-test-utils@15.4.1 requires a peer of react-dom@^15.4.1 but none was installed.
126411 verbose If you need help, you may report this error at:
126411 verbose     <https://github.com/npm/npm/issues>
126412 warn react-hot-api@0.4.7 requires a peer of react@>=0.11.0 || ^0.14.0-rc but none was installed.
126413 verbose If you need help, you may report this error at:
126413 verbose     <https://github.com/npm/npm/issues>
126414 verbose stack Error: node-sass@3.10.0 postinstall: `node scripts/build.js`
126414 verbose stack Exit status 1
126414 verbose stack     at EventEmitter.<anonymous> (C:\Users\MOSHMA~1\AppData\Roaming\nvm\v7.2.0\node_modules\npm\lib\utils\lifecycle.js:255:16)
126414 verbose stack     at emitTwo (events.js:106:13)
126414 verbose stack     at EventEmitter.emit (events.js:191:7)
126414 verbose stack     at ChildProcess.<anonymous> (C:\Users\MOSHMA~1\AppData\Roaming\nvm\v7.2.0\node_modules\npm\lib\utils\spawn.js:40:14)
126414 verbose stack     at emitTwo (events.js:106:13)
126414 verbose stack     at ChildProcess.emit (events.js:191:7)
126414 verbose stack     at maybeClose (internal/child_process.js:885:16)
126414 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
126415 verbose pkgid node-sass@3.10.0
```

NEO does not require on react? (as in, do I have to install react by hand *and then* install neo?)

**Comment by andriytyurnikov** [comment]
@moshmage you have problem with node-sass, which, I believe has additional requirements in windows, it is not related to neo

**Comment by moshmage** [comment]
@andersonvom ow, my bad -- Seems I failed redundantly at reading a debug.log :D 
Thanks for spotting it out!
